name: CD Process Demo
on:
  push:
    branches:
      - feature/*
    tags:
      - v*.*.*
      - rc_*.*.*

jobs:   
  development:
    uses: pv-platforma/constantine/.github/workflows/runner.yaml@feat/oidc_metadata
    secrets: 
      code_artifact_access_key: "${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION_US_WEST_2 }}"
      code_artifact_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRODUCTION_US_WEST_2 }}
      code_artifact_domain: ${{ secrets.AWS_CODEARTIFACT_DOMAIN_PRODUCTION_US_WEST_2 }}
      code_artifact_owner: ${{ secrets.AWS_CODEARTIFACT_DOMAIN_OWNER_PRODUCTION_US_WEST_2 }}
      aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID_DEVELOPMENT_US_WEST_2 }}
      aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVELOPMENT_US_WEST_2 }}
    with:
      environment: "dev" # github environment
      region: "us-west-2"
      ecr_registry: "486329218230.dkr.ecr.us-west-2.amazonaws.com"
      k8s_namespace: "okrs"
      image_name: "okrs-api"
      k8s_cluster_name: "usw2-pf-dev"
    if: startsWith(github.ref_name, 'feature')