name: CD Process Demo
on:
  push:
    branches:
      - feature/*
    tags:
      - v*.*.*
      - rc_*.*.*

jobs:   
  development:
    runs-on: ubuntu-latest
    steps:
      - name: dev-dynamic-loader
        run: |
          echo "Deployment env - development"
        shell: bash
    if: startsWith(github.ref_name, 'feature')
