name: Demo CI/CD
on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0
      
      - id: script
        uses: vinay-20/composite_actions/.github/pv-composite-actions/container-image@v1.0.3
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          session_token: ${{ secrets.AWS_SESSION_TOKEN }}

