name: Demo CI/CD
on:
  push:
    branches:
      - main
    tags:
      - lkgba_*.*.*
      - v*.*.*

# on:
#   pull_request:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0
      
      - id: development
        uses: vinay-20/composite_actions/.github/pv-composite-actions/container-image@main
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          #service_name: ${{ github.event.repository.name }}
          service_name: "dev-okrs-api"
          environment: "development"
          ecr_registry: "dev-registry"
        if: ${{  github.ref_name }} == 'main'

      - id: staging
        uses: vinay-20/composite_actions/.github/pv-composite-actions/container-image@main
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          #service_name: ${{ github.event.repository.name }}
          service_name: "dev-okrs-api"
          environment: "staging"
          ecr_registry: "staging-registry"
        if: startsWith(${{  github.ref_name }}, 'refs/tags/lkgba')

      - id: production
        uses: vinay-20/composite_actions/.github/pv-composite-actions/container-image@main 
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          #service_name: ${{ github.event.repository.name }}
          service_name: "dev-okrs-api"
          environment: "production"
          ecr_registry: "production"
        if: startsWith(${{  github.ref_name }}, 'refs/tags/v')