name: Demo CI/CD
on:
  push:
    branches:
      - main
    tags:
      - lkgba_*.*.*
      - v*.*.*

# on:
#   pull_request:
env:
  IMAGE_TAG: ${{  github.ref_name }}

jobs:
  development:
    if: ${{  github.ref_name }} == 'main'
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0
      
      - id: container-image
        uses: vinay-20/composite_actions/.github/pv-composite-actions/container-image@main
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          #service_name: ${{ github.event.repository.name }}
          service_name: "dev-okrs-api"
          environment: "development"
          ecr_registry: "dev-registry"
          image_tag: "lkgb"
  staging:
    if: startsWith(${{  github.ref_name }}, 'refs/tags/lkgba')
    runs-on: ubuntu-latest
    steps:  
      - id: staging
        uses: vinay-20/composite_actions/.github/pv-composite-actions/container-image@main
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          #service_name: ${{ github.event.repository.name }}
          service_name: "dev-okrs-api"
          environment: "staging"
          ecr_registry: "staging-registry"
          image_tag: ${IMAGE_TAG}

  production:
    if: startsWith(${{  github.ref_name }}, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:  
      - id: production
        uses: vinay-20/composite_actions/.github/pv-composite-actions/container-image@main 
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          #service_name: ${{ github.event.repository.name }}
          service_name: "dev-okrs-api"
          environment: "production"
          ecr_registry: "production"
          image_tag: ${IMAGE_TAG}
  
  outputs:
    runs-on: ubuntu-latest
    steps:
      - name: output vars
        run: |
          echo ${{  github.ref_name }}
        shell: bash