name: Development CI/CD
on:
  push:
    branches:
      - main

# on:
#   pull_request:
jobs:
  setting_env_vars:
    runs-on: ubuntu-latest

    outputs:
      access_key: ${{ steps.access-key.outputs.AWS_ACCESS_KEY}}
      secret_key: ${{ steps.access-key.outputs.AWS_SECRET_KEY}}
      session_token: ${{ steps.access-key.outputs.AWS_SESSION_TOKEN}}

    steps:
      - name: setting-access-key
        id: access-key
        run: |
          echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> $GITHUB_OUTPUT
        shell: bash
      - name: setting-secret-key
        id: secret-key
        run: |
          echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> $GITHUB_OUTPUT
        shell: bash
      - name: setting-session-token
        id: session-token
        run: |
          echo "AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}" >> $GITHUB_OUTPUT
        shell: bash
      
      - name: outputs
        id: outputs
        run: |
          echo "demo-app : ${{ secrets.AWS_ACCESS_KEY }}"
          echo "demo-app : ${{ secrets.AWS_SECRET_KEY }}"
          echo "demo-app : ${{ secrets.AWS_SESSION_TOKEN }}"
        shell: bash

  build-container-image:

    needs: setting_env_vars

    uses: vinay-20/reusable_workflows/.github/workflows/image_builder.yaml@main
    secrets:
      aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
    with:
      # aws_access_key: ${{ needs.setting_env_vars.outputs.access_key }}
      # aws_secret_key: ${{ needs.setting_env_vars.outputs.secret_key }}
      # aws_session_token: ${{ needs.setting_env_vars.outputs.session_token }}
      # limitation of github (https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations)
      # Cannot propogate environment variables to different workflows, hence aws_region needs hard coding.
      aws_region: "us-west-2" 
      #service_name: ${{ github.event.repository.name }}
      service_name: "dev-okrs-api"
      environment: "development"
      ecr_registry: "dev-registry"
      image_tag: "lkgb"
