name: Development CI/CD
on:
  push:
    branches:
      - main

# on:
#   pull_request:
env:
  IMAGE_TAG: ${{  github.ref_name }}
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
  build-container-image:
    uses: vinay-20/reusable_workflows/.github/workflows/image_builder.yaml@main
    with:
      aws_access_key: ${AWS_ACCESS_KEY}
      aws_secret_key: ${AWS_SECRET_KEY}
      aws_session_token: ${AWS_SESSION_TOKEN}
      # limitation of github (https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations)
      # Cannot propogate environment variables to different workflows, hence aws_region needs hard coding.
      aws_region: "us-west-2" 
      #service_name: ${{ github.event.repository.name }}
      service_name: "dev-okrs-api"
      environment: "development"
      ecr_registry: "dev-registry"
      image_tag: "lkgb"
      operation: "image"