name: CI/CD Development Environment
on:
  push:
    branches:
      - feature/*
      - main
    tags:
      - v*.*.*

jobs:
  development:
    uses: vinay-20/reusable_workflows/.github/workflows/deployment-orchestrator.yaml@main
    secrets: inherit
    with:
      environment: "dev"
      region: "us_west_2"
    if: ${{ github.ref == 'ref/head/feature' }}
  
  staging:
    uses: vinay-20/reusable_workflows/.github/workflows/deployment-orchestrator.yaml@main
    secrets: inherit
    with:
      environment: "stage"
      region: "us_west_2"
    if: ${{ github.ref == 'ref/head/main' }}

  production_us_west_2:
    uses: vinay-20/reusable_workflows/.github/workflows/deployment-orchestrator.yaml@main
    secrets: inherit
    with:
      environment: "prod"
      region: "us_west_2"
    if: startsWith(github.event.ref, 'refs/tags/v')

  # production_eu_central_1:
  #   uses: vinay-20/reusable_workflows/.github/workflows/deployment-orchestrator.yaml@main
  #   secrets: inherit
  #   with:
  #     environment: "prod"
  #     region: "eu_central_1"
